all:
	pdflatex presentation
	bibtex presentation
	pdflatex presentation
	pdflatex presentation

clean:
	rm -f presentation.aux presentation.log presentation.nav presentation.out presentation.pdf presentation.snm presentation.toc

